title: "El Políptico"
author: "Martín Cuentacanas"
description: "De momento, una gran nada."

show_excerpts: true
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title/

#########################################################################################
######### NO MODIFICAR #########
#########################################################################################
theme: "minima"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
      layout: post
